# Update workflow
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Generate SBOM from the dependencies (scanning the workspace directory)
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          upload-artifact: false
          upload-release-assets: false
          format: 'spdx-json'
          output-file: 'sbom.spdx.json'

      # Build the site using the build script in package.json
      - name: Build site
        run: npm run build

      # Package the build into a tarball so it can be easily verified
      - name: Package the build
        run: tar -czf dist.tar.gz dist

      # Commented out, as the SBOM version includes more detail.
      # - name: Attest Build Provenance
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path: "dist.tar.gz"

      # Complete an attestation of the SBOM and the build
      - uses: actions/attest-sbom@v1
        with:
          subject-path: 'dist.tar.gz'
          sbom-path: 'sbom.spdx.json'

      # Publish the SBOM (Zipped per https://github.com/actions/upload-artifact?tab=readme-ov-file#zip-archives)
      - name: Publish the SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

      # Publish the build
      - name: Publish the build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.tar.gz

  # Deploy job
  # deploy:
  #  # Add a dependency to the build job
  #  needs: build

  #  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #  permissions:
  #    pages: write      # to deploy to Pages
  #    id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
  #  environment:
  #    url: ${{ steps.deployment.outputs.page_url }}
  #    name: github-pages

    # Specify runner + deployment step
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy to GitHub Pages
  #      id: deployment
  #      uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
